### ISSUE TITLE
As a user, I want to be able to work on quests

### ISSUE THREAD

**Issue by Yamarik1** [Yamarik1/CMSC447-RPG-04#8]
This includes main and side quests.

**Comment by Yamarik1** [comment]
This story refers more to the general skeleton of the quest system, rather than the specific quests.

**Comment by Yamarik1** [comment]
Tests for this story are found in the homepage app. To run, use the command 'python manage.py test homepage.tests'.

**Comment by dustyMa** [comment]
There short test to check if main quest page exists is under the homepage app. To run, use the command 'python manage.py test homepage.tests'.
